Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job             count    min threads    max threads
------------  -------  -------------  -------------
all                 1              1              1
index_genome        1              1              1
total               2              1              1

Select jobs to execute...

[Sun May 11 15:47:42 2025]
rule index_genome:
    input: ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    output: ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.amb, ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.ann, ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.bwt, ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.pac, ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.sa
    log: logs/bwa_index/Homo_sapiens.GRCh38.dna.primary_assembly.fa.log
    jobid: 1
    reason: Missing output files: ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.ann
    wildcards: genome=Homo_sapiens.GRCh38.dna.primary_assembly, alg=fa
    resources: tmpdir=/tmp

/home/yoyo458/conda/envs/wgsEnv/bin/python3.12 /mnt/c/Users/Yahya/Documents/AutomatedWGSSnakemakeHPC/orchestration-layer/buckets/snakemake-files/.snakemake/scripts/tmpi4apv3ir.wrapper.py
[Sun May 11 15:47:43 2025]
Error in rule index_genome:
    jobid: 1
    input: ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    output: ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.amb, ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.ann, ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.bwt, ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.pac, ../data/reference/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.sa
    log: logs/bwa_index/Homo_sapiens.GRCh38.dna.primary_assembly.fa.log (check log file(s) for error details)
    conda-env: /mnt/c/Users/Yahya/Documents/AutomatedWGSSnakemakeHPC/orchestration-layer/buckets/snakemake-files/.snakemake/conda/f74f1eb2da98d809fb6ae66d5e2274f9_

RuleException:
CalledProcessError in file /mnt/c/Users/Yahya/Documents/AutomatedWGSSnakemakeHPC/orchestration-layer/buckets/snakemake-files/reference-build.smk, line 29:
Command 'set -euo pipefail;  /home/yoyo458/conda/envs/wgsEnv/bin/python3.12 /mnt/c/Users/Yahya/Documents/AutomatedWGSSnakemakeHPC/orchestration-layer/buckets/snakemake-files/.snakemake/scripts/tmpi4apv3ir.wrapper.py' returned non-zero exit status 1.
  File "/mnt/c/Users/Yahya/Documents/AutomatedWGSSnakemakeHPC/orchestration-layer/buckets/snakemake-files/reference-build.smk", line 29, in __rule_index_genome
  File "/home/yoyo458/conda/envs/wgsEnv/lib/python3.12/concurrent/futures/thread.py", line 59, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2025-05-11T154741.833651.snakemake.log
